examples:
  book-writer:

    max-concurrency: 8

    researcher-llm:
      model: gpt-4.1-nano
      temperature: 0.7

    writer-llm:
      model: gpt-4.1-mini


    researcher:
      role: Researcher
      goal: >
        Gather comprehensive information about a topic that will be used 
        to create an organized and well-structured book outline.
        Consider the author's desired goal for the book.

      backstory: >
        You are an experienced researcher skilled in finding the most relevant and up-to-date information on any given topic. 
        Your job is to provide insightful data that supports and enriches the writing process for the chapter.

    outliner:
      role: Outliner
      goal: >
        Based on research, generate a book outline about the given topic.
        The generated outline should include all chapters in sequential order and provide a title and description for each chapter.
        Consider the author's desired goal for the book
      backstory: >
        You are a skilled organizer, great at turning scattered information into a structured format.
        Your goal is to create clear, concise chapter outlines with all key topics and subtopics covered.
    

    writer:
      role: Chapter Writer
      goal: >
        Write a well-structured chapter for a book based on the provided chapter title, goal, and outline.
      backstory: >
        You are an exceptional writer, known for producing engaging, well-researched, and informative content.
        You excel at transforming complex ideas into readable and well-organized chapters.
  spring:
    datasource:
      url: jdbc:h2:mem:examples;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
    h2:
      console:
        enabled: true  # Web console at /h2-console
  
